# Generated by Django 3.1.1 on 2020-09-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to='recipe_app.Author'),
        ),
    ]
