# Generated by Django 3.1.1 on 2020-09-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_auto_20200910_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='favorite',
        ),
        migrations.AddField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to='recipe_app.Author'),
        ),
    ]
